services:
  api:
    build: .
    image: api-express:1.0
    container_name: first-app
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db/${DATABASE_DB}?schema=public
    command: npm run migrate
  db:
    image: postgres:15
    container_name: first-app-db
    environment:
      POSTGRES_DB: ${DATABASE_DB}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - 5432:5432
