name: Run Database Connection Test

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Load Environment Variables
        run: |
          echo 'DATABASE_DB="${{ secrets.DATABASE_DB }}"' >> .env
          echo 'DATABASE_USER="${{ secrets.DATABASE_USER }}"' >> .env
          echo 'DATABASE_PASSWORD="${{ secrets.DATABASE_PASSWORD }}"' >> .env
          echo 'DATABASE_HOST="${{ secrets.DATABASE_HOST }}"' >> .env

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose
          docker-compose up -d

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Tear down Docker Compose
        run: docker-compose down
